# Generated by Django 5.1 on 2024-08-25 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок поста')),
                ('content', models.TextField(verbose_name='Контент поста')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания поста')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления поста')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аавтор поста')),
            ],
        ),
    ]
