# Generated by Django 5.1 on 2024-08-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='cash',
            field=models.PositiveIntegerField(default=100, verbose_name='Кеш кошелька'),
        ),
    ]
