# Generated by Django 5.1 on 2024-08-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='Alexei', max_length=100, verbose_name='Имя заказчика'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='Timashkov', max_length=100, verbose_name='Фамилия заказчика'),
        ),
    ]
