# Generated by Django 5.1 on 2024-08-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_order_first_name_order_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(default=1, verbose_name='Общая цена заказа'),
        ),
    ]
