# Generated by Django 5.1 on 2024-08-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(default=1, max_length=255, verbose_name='Адрес доставки'),
            preserve_default=False,
        ),
    ]
